Updates to give a better out-of-the-box experience
Why
---

- What we had was working but was overly simplistic

This change addresses the need by
---------------------------------

- Adding serverless directory with workable and sane defaults
- What we had was working but was overly simplistic\l
- Modernizing the Makefile
- Spliting out python and serverless versions from testing
- Adding AWS_REGION as a choice

diff --git a/{{cookiecutter.project_name}}/Makefile b/{{cookiecutter.project_name}}/Makefile
--- a/{{cookiecutter.project_name}}/Makefile
+++ b/{{cookiecutter.project_name}}/Makefile
@@ -1,8 +1,17 @@
+{%- if cookiecutter.serverless_version == '1.27.2' -%}
+	{%- if cookiecutter.python_version == '3.6' -%}
 NAME = "verypossible/serverless:{{cookiecutter.serverless_version}}"
+	{%- endif %}
+{%- elif cookiecutter.python_version == '3.6' -%}
+NAME = "verypossible/serverless:{{cookiecutter.serverless_version}}-python3"
+{%- else -%}
+NAME = "verypossible/serverless:{{cookiecutter.serverless_version}}"
+{%- endif %}
 
 ENVDIR=envs
-LIBS_DIR=serverless/lib
-
+SERVERLESS_DIR=serverless
+LIBS_DIR=$(SERVERLESS_DIR)/lib
+SLS_ARGS=
 
 run = docker run --rm -it \
 		-v `pwd`:/code \
@@ -11,7 +20,7 @@ run = docker run --rm -it \
 		--name={{cookiecutter.project_name}}-$(ENV) $(NAME) $1
 
 
-shell : check-env env-dir
+shell : guard-ENV env-dir
 	$(call run,bash,$(ENV))
 .PHONY: shell
 
@@ -28,9 +37,10 @@ clean :
 libs :
 	@test -d $(LIBS_DIR) || mkdir -p $(LIBS_DIR)
 	pip install -t $(LIBS_DIR) -r requirements.txt
-	rm -rf $(LIBS_DIR)/*.dist-info
+	rm -rf $(LIBS_DIR)/*.dist-info $(LIBS_DIR)/boto*
 	find $(LIBS_DIR) -name '*.pyc' | xargs rm
 	find $(LIBS_DIR) -name tests | xargs rm -rf
+	(cd $(SERVERLESS_DIR) && test -f package.json && npm install)
 .PHONY: libs
 
 # NOTE:
@@ -41,16 +51,16 @@ libs :
 #	To deploy a single function: make deploy function=FunctionName, where
 #		FunctionName is the named function in your serverless.yml file
 #
-deploy : check-env
+deploy : guard-ENV
 ifeq ($(strip $(function)),)
-	cd serverless && sls deploy -s $(ENV)
+	cd serverless && sls deploy -s $(ENV) $(SLS_ARGS)
 else
 	cd serverless && sls deploy function -s $(ENV) -f $(function)
 endif
 .PHONY: deploy
 
-
-check-env:
-ifndef ENV
-	$(error ENV is undefined)
-endif
+guard-%:
+	@ if [ "${${*}}" = "" ]; then \
+		echo "\033[31mEnvironment variable $* required but not set\033[0m"; \
+		exit 1; \
+	fi
